name: Remote SSH Command

on: [push]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Multiple command
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.AWS_HOSTNAME }}
          username: ${{ secrets.AWS_USER_NAME }}
          key: ${{ secrets.AWS_PRIVATE_KEY }}
          port: 22
          script: |
            docker stop web1 && docker rm web1 && docker rmi hskull55/galeria
            docker run -d -p 80:5000 --name web1 hskull55/galeria
