name: Remote SSH Command

env:
  IMAGE_NAME: hskull55/galeria
  # FILES: compose.yml
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: Deploy en AWS
    runs-on: ubuntu-latest
    steps:
      - name: Multiple command
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.AWS_HOSTNAME }}
          username: ${{ secrets.AWS_USER_NAME }}
          key: ${{ secrets.AWS_PRIVATE_KEY }}
          port: 22 # ${{ secrets.PORT }}
          script: |
            docker rm -f web1
            docker rmi ${{ env.IMAGE_NAME }}
            docker run -d -p 80:5000 --name web1 ${{ env.IMAGE_NAME }}
